services:
    ## services for lavalink
    lavalink:
        container_name: lavamusic-lavalink
        image: ghcr.io/lavalink-devs/lavalink
        restart: on-failure
        environment:
            - SERVER_PORT=2333
        volumes:
            # mount application.yml from the same directory or use environment variables
            - ./Lavalink/application.yml:/opt/Lavalink/application.yml
            # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
            - ./Lavalink/plugins/:/opt/Lavalink/plugins/
        
        networks:
            - lavalink
        expose:
            # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
            - 2333
        ports:
            # you only need this if you want to make your lavalink accessible from outside of containers
            - "2333:2333"
        healthcheck:
            test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version'
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 10s

    #services for postgresql database
    postgres:
        container_name: lavamusic-postgres
        image: postgres:16
        restart: on-failure
        environment:
            POSTGRES_USER: lavamusic
            POSTGRES_PASSWORD: lavamusic
            POSTGRES_DB: lavamusic
        volumes:
            - lavamusic-data:/var/lib/postgresql/data:rw
        healthcheck:
            test: 'pg_isready -U lavamusic'
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 10s
        networks:
            - lavalink

    # services for lavamusic
    lavamusic:
        container_name: lavamusic
        image: ghcr.io/appujet/lavamusic:main
        environment:
            # lavalink nodes
            - NODES=[{"id":"Lavamusic","host":"lavalink","port":2333,"authorization":"youshallnotpass"}]
            # database url
            - DATABASE_URL=postgresql://lavamusic:lavamusic@postgres:5432/lavamusic
        env_file:
          - .env
        volumes:
            # mount .env from the same directory or use environment variables
            - ${PWD}/.env:/opt/lavamusic/.env
            - ./locales:/opt/lavamusic/locales
        restart: on-failure
        depends_on:
            lavalink:
                condition: service_healthy
        networks:
            - lavalink

volumes:
  lavamusic-data:
    external: true
    name: lavamusic-data

networks:
    lavalink:
        name: lavalink
