services:
  ## services for lavalink
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavamusic-lavalink
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: "-Xmx6G"
      SERVER_PORT: "2333"
      LAVALINK_SERVER_PASSWORD: "youshallnotpass"
    volumes:
      # mount application.yml from the same directory or use environment variables
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    healthcheck:
      test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    #expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      #- "2333"
    #ports:
      # you only need this if you want to make your lavalink accessible from outside of containers
      #- "2333:2333"

  # services for postgresql database
  postgres:
    image: postgres:16
    container_name: lavamusic-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lavamusic
      POSTGRES_PASSWORD: lavamusic
      POSTGRES_DB: lavamusic
    volumes:
      - lavamusic-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: 'pg_isready -U lavamusic'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - lavalink

  # services for lavamusic
  lavamusic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lavamusic
    restart: unless-stopped
    depends_on:
      lavalink:
        condition: service_healthy
    environment:
        # lavalink nodes
        - NODES=[{"id":"Lavamusic","host":"lavalink","port":2333,"authorization":"youshallnotpass"}]
        # database url
        - DATABASE_URL=postgresql://lavamusic:lavamusic@postgres:5432/lavamusic

    volumes:
      # mount .env from the same directory or use environment variables
      - .env:/opt/lavamusic/.env
      - ./locales:/opt/lavamusic/locales
    networks:
      - lavalink

volumes:
  lavamusic-data:
    external: true
    name: "lavamusic-data"

networks:
  lavalink:
    name: lavalink
